### ISSUE TITLE
Guardband/Channel spacing for contiguous component carrier

### ISSUE THREAD

**Issue by SawadaSyahmi** [Unipisa/Simu5G#106]
Hi developers, 

I wish to simulate a network with two contiguous carrier components. Is there any way to change the channel spacing/ guardband allocation from the channel bandwidth in between the carrier component?

Thank you for attending to my question.

Best Regards.

**Comment by giovanninardini** [comment]
Hello,
Simu5G models

**Comment by giovanninardini** [comment]
Hello,

in Simu5G, the physical layer is not completely modelled. Instead, it is abstracted using channel models. Thus, bandwidth and frequencies are modelled in an "abstract" way as well. You can configure the number of carrier components you wish, each using the desired bandwidth, and the MAC scheduler will consider those carrier components when scheduling transmissions. There is no concept of channel spacing between carrier components, simply because that would have no effects in the simulations.

Best regards.
Giovanni
