### ISSUE TITLE
issues with more than one CarrierComponent 

### ISSUE THREAD

**Issue by SawadaSyahmi** [Unipisa/Simu5G#116]
Hi developers,
Thank you for attending to my issue.

When using more than 1 carrier component in simu5G, the settings for the first carrier component is updated for all the carrier component, and it seems like the configuration for the other carrier component is overwritten. 

![image](https://user-images.githubusercontent.com/86639833/220233955-1ccfaa2d-c196-4628-8823-312b56ba685a.png)

I found the problem when the throughput drop as expected when `tddNumSymbolsDl` on the `componentCarrier[0] ` when the configuration is changed from 7 to 4 but there are no changes when the `tddNumSymbolsDl` on the `componentCarrier[1]` changed. 

How can I change the `tddNumSymbolsDl` on the `componentCarrier[1]`?

Thank you and best regards,

**Comment by giovanninardini** [comment]
Hello,

please note that the current behavior at the MAC layer of the gNB is to schedule all UEs on the first available component carrier, and only using the second component carrier if the first one used its whole capacity. So, it might be that you cannot observe any difference in the results when changing the configuration of the second component carrier just because it is not used or used only partially.

**Comment by SawadaSyahmi** [comment]
Hi Dr. Nardini,

Thank you so much for the clarification.
Can you help to pin out the source file where I can find the code segment where the second component carrier is used after the first one is at full capacity?

Thank you and Best regards.
