### ISSUE TITLE
How to handle an inet:indication* message ? 

### ISSUE THREAD

**Issue by zazim13** [Unipisa/Simu5G#149]
Hi, 
I am trying to write my own MEC and UE applications, but I am experiencing an error after a few time of simulation.
My UEApp is receiving an inet:indication* error  and I am not sure about what causes this.  
The error happens in my handlemessage function when I am trying to check and cast a received message to a inet:Packet. 
Considering that I am not sending this type of message from my MecApp, I suppose that it is a DeviceApp message.
It would be great to understand what triggers the sending of such a message type. 

Best regrads.

**Comment by giovanninardini** [comment]
Sometimes this error may be caused by some ICMP packet triggered by the IP layer because of some uncorrect IP address. You can start debugging by checking whether the IP addresses are assigned correctly in the network and that all the destination IP addresses in the application layer are configured correctly.

**Comment by zazim13** [comment]
Hi, thank you for your answer. I did a bunch of modifications (not related to this issue) in my code and I do not get this error anymore. In the case it occurs again, I will add details of debugging here.   
Hakim
