### ISSUE TITLE
Strange processing time with fair sharing mode enabled

### ISSUE THREAD

**Issue by zazim13** [Unipisa/Simu5G#162]
Hi, 
I am experiencing strange processing time using  vim->calculateProcessingTime() with fair sharing mode enabled. 
After some debugging I think that there is a problem with CPU units. The allocatedCPU variable has the same unit than virtualCpu parameter in the application descriptor Json, which should be MIPS from [this answer](https://github.com/Unipisa/Simu5G/issues/139#issuecomment-1497066828).  Than the maxCpuSpeed parameter that should be in MIPS also [from here](https://github.com/Unipisa/Simu5G/blob/6365f941b3ef9ecf2cc2cfac071e1684db8ed912/src/nodes/mec/MECHost.ned#L39), is converted[ here](https://github.com/Unipisa/Simu5G/blob/6365f941b3ef9ecf2cc2cfac071e1684db8ed912/src/nodes/mec/VirtualisationInfrastructureManager/VirtualisationInfrastructureManager.cc#L48) in instruction per second. 
This is problematic when using fair sharing mode because the values are divided.
It must also be problematic for admission control and must answer my precedent issue #160
Sincerely 
Hakim

**Comment by linofex** [comment]
Hi, you are right. A conversion of the value in the JSON descriptor is needed somewhere. In order to manage all the vales in MIPS I decided to remove the conversion everywhere but the time calculation.  This will fixed in a next commit, but for now you can:

remove the `pow`  multiplication [here](https://github.com/Unipisa/Simu5G/blob/6365f941b3ef9ecf2cc2cfac071e1684db8ed912/src/nodes/mec/VirtualisationInfrastructureManager/VirtualisationInfrastructureManager.cc#L48) and [here](https://github.com/Unipisa/Simu5G/blob/6365f941b3ef9ecf2cc2cfac071e1684db8ed912/src/nodes/mec/VirtualisationInfrastructureManager/VirtualisationInfrastructureManager.cc#L501). Next, the time calculation in  [calculateProcessingTime](https://github.com/Unipisa/Simu5G/blob/6365f941b3ef9ecf2cc2cfac071e1684db8ed912/src/nodes/mec/VirtualisationInfrastructureManager/VirtualisationInfrastructureManager.cc#L534) method becomes:
`time = numOfInstructions/(pow(10,6)*currentSpeed);` in both the modes.

Let me know if everything gets solved,

best regards,

Alessandro

**Comment by giovanninardini** [comment]
This has been fixed by commit [b4e2b2f](https://github.com/Unipisa/Simu5G/commit/b4e2b2fbe3bf5f08a8e3666f3581607403965add)
