### ISSUE TITLE
Is there any documentation related to the project?

### ISSUE THREAD

**Issue by daohu527** [Unipisa/Simu5G#22]
I am a Simu5G beginner and I want to try to use it. I look into the official web and found few descriptions, it's hard to read all the code.

Is there any relevant interface documentation or examples, any help would be great！

**Comment by giovanninardini** [comment]
Hello, unfortunately there is no official documentation describing all the interfaces.
You can find some useful information regarding the modelling of the simulator into the papers we published: http://simu5g.org/related.html
Also papers about SimuLTE may contains relevant information, since Simu5G shares its architecture with it.

Best regards.

**Comment by daohu527** [comment]
Thank you for your reply! I will read this papers soon
