### ISSUE TITLE
Omnet++: Unable to configure server(StandardHost) for Dynamic Ue

### ISSUE THREAD

**Issue by manishkjain21** [Unipisa/Simu5G#24]
Hello All,

I am working on omnet++ along with Simu5G and INET. I have modified the SingleCell Network from Simu5G to include dynamic Nodes. The SingleCell network has a server(StandardHost from Inet). I am able to add and remove Ue (simu5g.nodes.Ue) from the network and also associate the UE with eNobeB. But the server is unable to transmit data to the dynamic Ues. this is due to the fact that it does not known destination address. 

Is there a way we give the server dynamic address for sending the data? 

Any help would be appreciated.

**Comment by giovanninardini** [comment]
Hello,

you can directly set the module name of the receiving as the destination address of the server application. The IPv4NetworkConfigurator will automatically translate it to an IP address.

In case of dynamically-created nodes, you just need to make sure that the application starts sending to the receiver after it has been created, otherwise an exception will be thrown. 
See the code of apps/voip/VoIPSender,cc as an example - [initTraffic()](https://github.com/Unipisa/Simu5G/blob/ffbdda3e4cd873b49d7022912fe25e39d1a503e8/src/apps/voip/VoIPSender.cc#L84) function.  

Best regards.
Giovanni
