### ISSUE TITLE
MEC connections and network stats request from UE

### ISSUE THREAD

**Issue by Devastation** [Unipisa/Simu5G#35]
Hello!

I'm currently implementing a following simulation scenario: one UE traverses between two gNBs, therefore experiencing a handover. This UE **constantly sends packets to the MEC host**. MEC host acts like a control instance and data processor, however it also periodically responds to UE back and **send current network state** to it.

So I write a custom UeApp, use a standard DeviceApp and want to modify a standard MecAppBase, which should be able to send network state together with some reaction (as enum) for the processed incoming UE's data back to this UE. My questions:

1. Why do in some examples a single mecHost is connected directly to a gNB and in some (e.g. simulations/NR/mec/multiMecHost or emulation/mec/...) it is connected to a UPF through a router? Is the last case just simply equivalent to have a simple server aka standardHost instead of a MEC one? 

2. How can I constantly deliver a network state (delay, plr, tpt etc) to an UE? I can watch rtt or so on the UE side as signals for sure, but I want to know the end-to-end network state before UE has decided to send some data to MEC. I thought it is possible with RNIService of MEC, but in the example simulations/NR/mec/RNIDelay, which seems like very close to what I want to implement from a first impression, the RNIDelayApp for UE is commented and is replaced by a simple UDPVideoClient together with a server acting like a video server, while at the same time MECApp is not pointed in omnetpp.ini at all, looks like MEC is not used at all in this example...

Thanks in advance

Cheers,
Charlie

**Comment by linofex** [comment]
Hi Charlie,
about your questions:

1. The mecHost has all the interfaces allowing to be deployed everywhere in the core network. The two scenarios you mentioned are pretty much the same. In the emulation example, the mecHost is connected to a router just to organize in a better way the network and the routing tables. A mecHost can be seen as a server, but it has also the MEC service features (e.g RNIS and Location Service) 

2. The current example in the RNIDelay scenario has been used to test some modules that implement the RNI service. The RNIDelayApp was commented during the debug phase. Maybe I will update the scenario to make it clearer (thank you for pointing this out). To answer your question, you should implement a MEC app that requests network information to the RNI service (via the RESTful API). The latter implements the L2 measurements resource of the standard (see ETSI GS MEC 012 V2.1.1 (2019-12)). The MEC app then parses the JSON response and sends a message to the UE App.

I hope I have been helpful.
Best regards, 
Alessandro

**Comment by Devastation** [comment]
Hi Alessandro,
> <cite>The mecHost has all the interfaces allowing to be deployed everywhere in the core network. </cite>

It confuses me even more, because at least from my understanding the very basic idea of MEC is that it serves the user on the edge, meaning "before" the core network. But do I understand correctly, that considering MEC implementation in Simu5G, it doesn't matter (at all?), where do you place mecHost module in network topology, i.e., in .ned file: directly connected to gNB(s) or only to UPF, right?

> <cite>To answer your question, you should implement a MEC app that requests network information to the RNI service (via the RESTful API). </cite>

Ok, thank you, this is clear. However, would be cool, if there would be an end-to-end example of using RNIService with decoding the response and so on.

**Comment by linofex** [comment]
Hi Charlie, 
you are right, MEC is supposed to be placed nearer the UE as possible, at the edge. When I talk about 5G Core Network I refer to the "area" between the RAN and the Data Network, where all the entities (UPF and network functions) that manage the mobile network are present. By the way, a MEC host can be deployed everywhere, according to the needs of the operators (I suggest you read this [white paper](https://www.etsi.org/images/files/ETSIWhitePapers/etsi_wp28_mec_in_5G_FINAL.pdf) to clear your doubts).
In Simu5G you can deploy the MEC host as you prefer since the MEC host also has inside the interface to handle GTP connections.


In the next days, I will upload some commits with updates about the MEC framework and I hope to also add a RNI service scenario. Meanwhile, you can take a look at the "WarningAlertApp" example (src/apps/mec/WarningAlert) where the HTTP response is handled. The framework uses the [nlohmann JSON](https://github.com/nlohmann/json) library to handle JSON data.

**Comment by Devastation** [comment]
Thanks a lot!
