### ISSUE TITLE
Maximum number of vehicles that singleMecHost can support?

### ISSUE THREAD

**Issue by daohu527** [Unipisa/Simu5G#44]
I modified the number of cars by `**.numCars = 100`  in `simulations\NR\mec\singleMecHost\omnetpp.ini`. Then I face some error, since any value greater than 100 gives an error, I searched for 100, and adjusted `*.mecHost.maxMECApps`.

Next, I tried to adjust the number of cars, I could reach 266, but then it would report an error, I began to suspect that it was the IP address, but since 266 is greater than 255, it might be another problem.

could you please give me some advice? I want to run `**.numCars = 400` by one station
I also add `**.hasRNISupport = false`

**Comment by giovanninardini** [comment]
Hello, 

could you please provide more details about the error?

**Comment by daohu527** [comment]
The error message like below
```
## numcar > 100
<!> LCM proxy responded 500 -- in module (DeviceApp) singleMecHost.car[8].app[0] (id=731), at t=1.0545s, event #1848833
<!> LCM proxy responded 500 -- in module (DeviceApp) singleMecHost.car[11].app[0] (id=834), at t=1.0545s, event #1387129
```

**Comment by daohu527** [comment]
Yes, I have added the mec resource, but the error still appears. eg in the `simulations\NR\mec\singleMecHost\omnetpp.ini`
```
######################_ME Host Side_#####################
# resources available
*.mecHost.maxMECApps = 400												#max ME Apps to instantiate
*.mecHost.maxRam = 320GB													#max KBytes of Ram Space 
*.mecHost.maxDisk = 100TB												#max KBytes of Ram Space 
*.mecHost.maxCpuSpeed = 400000					
```
I see that other configurations in the code do not take effect but `maxMECApps`

**Comment by linofex** [comment]
Hi, I didn't see you consider the `**.numCars ` parameter. The scenario in `simulations\NR\mec\singleMecHost\omnetpp.ini` does not contain it, but the parameter `**.numUes`. By changing it to 400 and setting the MEC host resources to the values you wrote in the last message, plus increasing the `maxCpuSpeed` par to a number greater than 400 * 1500 (MIPS of a MECWarningAlertApp, as in the appDescritor [file](https://github.com/Unipisa/Simu5G/blob/master/simulations/NR/mec/singleMecHost/ApplicationDescriptors/WarningAlertApp.json)),  I was able to run the `test` configuration simulation without errors.

**Comment by monologconnor** [comment]
> Hi, I didn't see you consider the `**.numCars ` parameter. The scenario in `simulations\NR\mec\singleMecHost\omnetpp.ini` does not contain it, but the parameter `**.numUes`. By changing it to 400 and setting the MEC host resources to the values you wrote in the last message, plus increasing the `maxCpuSpeed` par to a number greater than 400 * 1500 (MIPS of a MECWarningAlertApp, as in the appDescritor [file](https://github.com/Unipisa/Simu5G/blob/master/simulations/NR/mec/singleMecHost/ApplicationDescriptors/WarningAlertApp.json)), I was able to run the `test` configuration simulation without errors.

Hi @linofex, I'm actually getting the same error with @daohu527. Actually the `**.numCars` parameter does exist in the `omnetpp.ini` file, but not the `**.numUes`, since I'm using the virtual machine image with VirtualBox, provided in Simu5G's homepage, which contains `Simu5G 1.2.0`. I believe @daohu527 is using the virtual machine as well.

I'm considering error exists due to `1.2.0` version or some factor about virtual machine, so I'm have downloaded the latest source code and build the latest version of OmNet++ and do the simulation on Windows11 envrionment.  I have set the `**.numUes` to `400`, `*.mecHost.maxMECApps` to `500`, disabled the `**.hasRNIsupport` parameter, and set all UE's initialY position to 50m: `**.ue[*].mobility.initialY = meter(50)`. Also I kept the `maxCpuSpeed` unmodified.

I am now able to run the simulation without error, but there is some percentage that the simulation pops out an error contains description like `invalid signal ID`. I'm not sure on how that occurs, and how to reproduce that situation since it occurs randomly. I'm planning to try more about that.

Thanks for your help.

**Comment by linofex** [comment]
Hi @monologconnor , when the error about the `invalid signal ID` will occur again, please tell me which module triggered it. I already found such error and I thought I solved it.

Thanks

**Comment by monologconnor** [comment]
> Hi @monologconnor , when the error about the `invalid signal ID` will occur again, please tell me which module triggered it. I already found such error and I thought I solved it.
> 
> Thanks

Hi @linofex, thanks for your reply.
Actually I have encountered the `invalid signal ID` error again these days, and I captured screenshot on that, the `signalID` is not a fixed number though.

![屏幕截图 2022-05-09 111239](https://user-images.githubusercontent.com/38450642/167853412-62635934-e939-4ab8-b674-7042187063b5.png)
![屏幕截图 2022-05-09 142127](https://user-images.githubusercontent.com/38450642/167853419-a8ec1f77-33a1-4fd7-a5b9-1d5d5a4be717.png)

It shows that the error was triggered from `ServiceRegistry` module.

**Comment by linofex** [comment]
Thank you, this is due to a signal is not registered in the ServiceRegistry class. To solve this, do the following (I will push a commit soon):
add
```
@signal[requestQueueSize];
@statistic[requestQueueSizeStat](title="Request queue size"; source="requestQueueSize"; record=mean,vector);
@signal[responseTime];
@statistic[responseTimeStat](title="Response time of foreground requests"; source="responseTime"; record=mean,vector);
```
in [this](https://github.com/Unipisa/Simu5G/blob/master/src/nodes/mec/MECPlatform/ServiceRegistry/ServiceRegistry.ned) file (in the `parameters` section).

add:
```
 requestQueueSizeSignal_ = registerSignal("requestQueueSize");
 responseTimeSignal_ = registerSignal("responseTime");
```

in [this](https://github.com/Unipisa/Simu5G/blob/master/src/nodes/mec/MECPlatform/ServiceRegistry/ServiceRegistry.cc#L78) file (in the `void ServiceRegistry::initialize(int stage)` method).

This should solve the issue.

**Comment by monologconnor** [comment]
> 

Thanks! I'll try it later!

Btw is the latest source code compatible with `Omnet++ 16.0 pre11` and `INET 4.3.2`? My project needs `Veins` as well so I am actually struggled with the selection of versions :(

**Comment by giovanninardini** [comment]
Release v1.2 of Simu5G is compatible with OMNeT++ 6.0pre11 and INET 4.3.2.

The latest master-branch code, instead, needs OMNeT++ 6.0 and INET 4.3.9.
