### ISSUE TITLE
MEC network analysis

### ISSUE THREAD

**Issue by ErosRibaga** [Unipisa/Simu5G#45]
Hi, what is the best way to get latency and jitter in a MEC network simulation?

Thank you in advance.

**Comment by giovanninardini** [comment]
Hello,

I assume you are interested in application-level metrics.
You need to add some timestamp to the messages transmitted by the sender application at the moment of their creation, and compute the difference at the receiver side. Take a look at the implementation of CBR and VoIP applications in Simu5G, which include a _frameDelay_ statistic that exactly measures the end-to-end latency.

**Comment by ErosRibaga** [comment]
Thank you for your reply, but I still have some issues.

I tried calculating the time it take to a message to go from an UE to the MecHost in the SingleMecHost example, and I have some questions about it.

### Q1
I worked on the WarningAlertApp and implemented this:

```cpp
//client side
void UEWarningAlertApp::sendMessageToMECApp() {
  alert->setPayloadTimestamp(inet::simTime());

// server side
void MECWarningAlertApp::initialize(int stage) {
    LatencySignal_ = registerSignal("Latenza");

void MECWarningAlertApp::handleUeMessage(omnetpp::cMessage *msg) {
  double delay = (simTime() - warnPk->getPayloadTimestamp()).dbl();            
        emit(LatencySignal_, delay);
        EV << "Latenza: " <<  delay;    

//MECWarningAlertApp.ned file
simple MECWarningAlertApp like IMECApp, IApp
{
    parameters:
        @signal[Latenza];
        @statistic[Latenza](title="Latenza"; unit="s"; source="Latenza"; record=vector, stats);
```

The command `EV << "Latency: " <<  delay; ` print the latency that is around 0.004s, but once the simulation is finished, the latency recorded values are equal to NaN.
I tried to print something in the function `void MECWarningAlertApp::initialize`, but I couldn't see anything printed, so I think the problem is that the signal is not registered correctly.
What do you think about it?

### Q2
What are  RequestForegroundApp and RequestBackgroundApp used for?

### Q3
What are UPF e iUPF used for?

**Comment by giovanninardini** [comment]
Hello,

**Q1:**
I guess that it is because the omnetpp.ini sets the warmup period to 10s.
In the _WarningAlertApp_ you are considering you are trying to measure the delay of a message that is sent only once, at the beginning of the simulation. You should be able to see the values in the statistics by setting a shorter warmup period, e.g. `warmup-period = 0s`

**Q2:**
_RequestForeground/BackgroundApps_ are used to generate some traffic load to the MEC services without actually simulating the corresponing apps at the UE side. This is done to allow one to simulate heavier load on MEC services (hence, higher response times) without slowing down the simulation. 
You can find more detailed information in [this paper](https://arxiv.org/abs/2203.13511) (section 3.3).

**Q3:**
we use UPF as the termination endpoint of the GTP tunneling, that is the entry/exit point of the 5G core network. 
iUPF (which stands for intermediate UPF) is used just as a router within the 5G core network and forwards packets between gNBs, MEC hosts and the UPF.

**Comment by ErosRibaga** [comment]
What is the best way to get the delay for every message sent from the UE to the MecHost and vice versa?

I tried working with the WarningAlertPacket instead of the WarningAlertPacketStart, but it is instantiated as a const in the following piece of code, and I don't know how to communicate to the MecHost when the packet transmission started.

``` c++
void UEWarningAlertApp::handleInfoMEWarningAlertApp(cMessage* msg)
{
    inet::Packet* packet = check_and_cast<inet::Packet*>(msg);
    auto pkt = packet->peekAtFront<WarningAlertPacket>();
```

Should I create another packet to get what I want?

**Comment by giovanninardini** [comment]
**Q1**

You do not need to create new packets whose only purpose is to measure the delay. In general, in order to measure the end-to-end delay, just add the timestamp (if not already present) to every message sent by the sender app, then you read the timestamp in the application that receives that packet.
In this regard, maybe the WarningAlertApp is not the application you need, because it does not send packets "regularly": the UEWarningAlertApp sends one message at the beginning only, which works as a kind of "subscription" request. Then, the MECWarningAlertApp sends one message back only when the UE enters the "warning" zone. 

The piece of code you mention is the function that handles the _reception_ of the packet from the MECWarningAlertApp. There, you would need to _read_ the timestamp possibly added by the MECWarningAlertApp. So, the packet being const should not be a problem.

**Q2**

A selfMessage is a message that a module sends to itself and it is usually used as a timer (e.g., the module has to execute operation X in 1 second, I schedule a selfMessage in 1 second).
The handleSelfMessage is the function that is called when the selfMessage is received and performs the actions related to that message (in the example abobe, the handleSelfMessage would execute operation X)    

**Q3**

The handleMp1Message function is the one that performs the necessary operations upon the reception of a message from the MECPlatform, e.g., a message coming from a MEC service

**Comment by ErosRibaga** [comment]
Thanks for your response.

Could I use the RNIDelay example to achieve what I need?
I tried looking at the example but I don't understand if the mecHost applications are only used to generate some traffic or if the are used for something else.

**Comment by Ali-K-Abbas** [comment]
Add to extract words from web page

Hello Dear, @giovanninardini 
I followed the above Construction and was able to get results with a MEC Cbr App, using the independentMecApp  for 1 UE, However when I try to use multiple instances of the independentMecApp to multiple UEs (tested with 2 & 3 UEs) , Results only shows  for independentMecApp[0] , below is the parameters I am using for the app in .ini:

#########################_UE Side_#######################
*.ue[*].numApps = 1
*.ue[*].app[0].typename = "CbrSender"
*.ue[*].app[0].destAddress = "mecHost.virtualisationInfrastructure"
*.ue[*].app[0].localPort = 3000+ancestorIndex(0)

*.ue[*].app[0].PacketSize =${Pk=100,300,500,600, 1000}
# obtain the address of the client by reading its index in the array of udp Apps
*.ue[*].app[0].startTime = 0s
#*.ue[*].app[*].sampling_time = 1s
**.ue[*].app[0].finishTime = 38s
#*.ue[*].app[*].startTime = uniform(0s,0.02s)

#------------------------------------#

#============= Application Setup MEC receiver =============
**.numIndependentMecApp = ${nInApps}
*.mecHost.independentMecApp[*].typename = "MecCbrReceiverApp"
*.mecHost.independentMecApp[*].localUePort = 3000#+ancestorIndex(0)
*.mecHost.independentMecApp[*].mecAppIndex = 0
*.mecHost.independentMecApp[*].mecAppId = 0

#*.mecHost.independentMecApp[0].PacketSize = 500



**.numUe = ${nInApps=1,2,3}#,50,100,200}

*.mecHost.independentMecApp[*].requiredRam = 1B
*.mecHost.independentMecApp[*].requiredDisk = 1B
*.mecHost.independentMecApp[*].requiredCpu = 1}
