### ISSUE TITLE
multi upf support

### ISSUE THREAD

**Issue by imanazimi1997** [Unipisa/Simu5G#52]
Is it possible to connect several UPF to one gNB(for emulation)?

**Comment by imanazimi1997** [comment]
Tanks for answers
Why is it not received on the server side when emulating with two outputs, when packets is sent in a  without delay? Many of packet not received by upf. But if they are sent with a delay of, say, 1 second, will it be received?

**Comment by imanazimi1997** [comment]
Tanks for answers
Why is it not received on the server side when emulating with two outputs, when packets is sent in a  without delay? Many of packet not received by upf. But if they are sent with a delay of, say, 1 second, will it be received?

**Comment by giovanninardini** [comment]
Hello, 

could you please be a bit more specific about your problem? 
Are you running some emulation example in the Simu5G package? What outputs are you talking about? What delay are you talking about?

**Comment by imanazimi1997** [comment]
Yes, Sure. I run the simu5g  in a emulation mode so that the server and
client were external. On the client side, I sent 500 packets of 1000 bytes
to the server continuously with a loop. But most packets were not even
received by the server (even with tcp). Then I put a delay of one second
between sending each packet. And then it was completely received. Is this
problem solvable?

**Comment by giovanninardini** [comment]
I believe this is due to the fact that packets are sent too fast (I understand that you send 500 packets with no delay between each other), and the emulation is not able to run in real time anymore. That is, you are injecting too much traffic (all together) into the simulator, and it cannot parse all of it while maintaining the real-time requirement. 
Remember that real-time emulation is only possible when the complexity of the simulation is such that simulation time is able to run in parallel with wall-clock time (see the "note" [here](https://inet.omnetpp.org/docs/users-guide/ch-emulation.html))

On the other hand, when you send packets more slowly (i.e., using one-second interval), the emulation is able to keep the real-time pace and the server is able to receive packets.

**Comment by imanazimi1997** [comment]
Thanks for the tips.
The last question I have is whether it is possible to emulation multiple
mec scenario in simu5g?

**Comment by imanazimi1997** [comment]
Thanks
