### ISSUE TITLE
How to make 3 eNodeB send AirFrame at the same time in Simu5G?

### ISSUE THREAD

**Issue by grania38** [Unipisa/Simu5G#56]
Hello, I am new to OMNET++ and I am working on vanet simulation using Simu5G cars example. I already added another eNodeB Now I need to let them send messages at the same time to the car.
Any suggestions? 
Thank you

**Comment by giovanninardini** [comment]
Hello,

I am not sure I fully understand your question. If you mean trasmitting from several eNodeBs to the same car simultaneously, then it is not possible because the UE/Car can be attached to one eNodeB only at a given time (potentially performing handover during the simulation).

Best regards.
Giovanni
