### ISSUE TITLE
Is there a macCellThroughputDl measurement error?

### ISSUE THREAD

**Issue by hullopes** [Unipisa/Simu5G#66]
Hi there.
Running the /simu5G/simulations/NR/standalone_multicell/omnetpp.ini with different *.carrierAggregation.componentCarrier[*].numBands values, I expected to see higher throughput values increasing the bandwidth (6 to 50, e.g.), but I see in the results something strange. For instance:
for:
*.carrierAggregation.componentCarrier[*].numBands = 6
we get scalar MultiCell_Standalone.gnb1.cellularNic.mac macCellThroughputDl:mean 58152.100614993

for:
*.carrierAggregation.componentCarrier[*].numBands = 100
we get scalar MultiCell_Standalone.gnb1.cellularNic.mac macCellThroughputDl:mean 58082.317802289

**Comment by giovanninardini** [comment]
Hello,

the `numBands` parameter changes the available bandwidth provided by the cell (number of RBs).
The `macCellThroughput` statistic measures the total traffic that the cell was able to serve. This metric depends on the traffic generated by the UEs and on the number of available bands, but _only if_ the traffic was so high that the available bands were not enough to serve all the traffic generated by the UEs.
For example, if the traffic generated by the UEs only occupies 3 RBs, then the `macCellThroughput` statistic will not change by increasing the numBands parameter from 6 to 100, since the UEs will still occupy 3 RBs only. You can observe the `avgServedBlocks` metric to see how many bands, on average, were allocated.

**Comment by hullopes** [comment]
Thank you very much.
