### ISSUE TITLE
Obstacles

### ISSUE THREAD

**Issue by ArndtTU** [Unipisa/Simu5G#69]
Hello,

thank you for the simulator.
I do have a problem though. Is it possible to create obstacles that interfere with the radio propagation such as buildings etc.? Especially in higher frequency ranges such as above 25GHz. I am using Simu5G v1.1.0 and don't think I can move to another version at this point. I am also using Veins ans SUMO and as far as I know do the buildings created with SUMO not hinder the radio propagation.

Thanks for your help!

**Comment by giovanninardini** [comment]
Hello,

physical obstacles are not modelled within the simulator, and those created by SUMO are not considered. Channel models implemented within Simu5G follows 3GPP specifications, which I believe consider the complexity of the environment in some way. 
However, if you want to model physical obstacles accurately, you would need to implement a new channel model (or modify an existing one), so that it is aware of your "custom" objects in the environment. In other words, you would need a channel model whose mathematical model computes the power received by nodes by taking into account the presence of obstacles.
