### ISSUE TITLE
PCAP Recording

### ISSUE THREAD

**Issue by buraksenkus** [Unipisa/Simu5G#7]
Hi,
I've integrated Veins with Simu5G and I can run **cars** scenario inside `simulations/NR`. 
I want to record messages which transmitted by cars and gNodeBs into individual pcap files. As I understand from [this guide](https://inet.omnetpp.org/docs/showcases/general/pcaprecording/doc/), it is possible to do that by setting some pcap parameters in `omnetpp.ini`.

I've added below lines into `omnetpp.ini`
```ini
*.car[*].numPcapRecorders = 1
*.car[*].pcapRecorder[0].pcapFile = "results/car[*].pcap"
*.car.pcapRecorder[*].pcapLinkType = 108      # ethernet
```

After running scenario, it saves an empty pcap file. Probably it is related with **pcapLinkType** parameter. 
- Which **pcapLinkType** value should I use?
- Are there any more parameters that I have to add?
- Also, how can I save pcaps as separate files for each node? How should I set **pcapFile** parameter?

**Comment by giovanninardini** [comment]
Hello,
by default, the INET's PCAP recorder tries to capture packets at layer2, as stated in the tutorial you linked, but our layer2 (i.e. the _cellularNic_) does not support that currently. You can try to capture packets at layer3 instead, like this:

```
*.car[*].numPcapRecorders = 1
*.car[*].pcapRecorder[0].pcapFile = "results/car[" +string(ancestorIndex(1)) +"].pcap"
*.car[*].pcapRecorder[0].moduleNamePatterns = "ipv4"
*.car[*].pcapRecorder[0].dumpProtocols = "ipv4"  
**.crcMode = "computed"
**.fcsMode = "computed"
```

**BUT....** at the moment you will not be able to use that with Simu5G's custom applications (e.g. VoIP or CBR), since they need some modifications too. You should use some of the INET's applications instead.

We will try to adapt our Simu5G code to make PCAP recording properly work. Thank you for raising this issue.

Giovanni

**Comment by buraksenkus** [comment]
Oh, I see. I'm looking forward for this feature to be available for Simu5G.

Thank you for your answer!
