### ISSUE TITLE
Cars communicating with a server (Question)

### ISSUE THREAD

**Issue by ZePinto99** [Unipisa/Simu5G#84]
I'm new to OMNet++, and I'm trying to simulate an edge vehicle network. I'm using the Simu5G virtual machine (Simu5G 1.2.1 PnP).

The objective is to have a car or multiple cars at different distances communicating with a server by a 5G network. This server would receive images from the cars, execute an AI model for object detection and return the image with the detections to the respective cars.
I'm trying to do this by adapting the example simulations/NR/cars, but I don't know how to add cars to the correct positions and start communications between cars and server.

The objective of this experiment is to benchmark response times. Is there any resource I can follow to do something like this? 

Best regards,
José Pinto

**Comment by giovanninardini** [comment]
Hello,
the "cars" example uses Veins and SUMO to pilot the mobility of vehicles. 
Their position within the simulation is assigned based on the given SUMO configuration specified by the XML files in the folder. I suggest to consult the SUMO documentation in order to build your road topology and the corresponding mobility of vehicles. 

The starting time of the communication between the cars and the server is configured by the `startTime` parameter of the application. You can add/modify that in the omnetpp.ini file.

Best regards.
Giovanni
